sudo: required
language: node_js

addons:
  packages:
    - openjdk-8-jdk
  chrome: stable

services:
  - docker

# Only build on master, stable branches and tag
# The stable branch and tag should be leading with numbers
branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

before_install:
  # https://github.com/golang/dep/blob/master/docs/FAQ.md#how-do-i-get-dep-to-authenticate-via-ssh-to-a-git-repo
  - git config --global url."git@github.ibm.com:".insteadOf "https://github.ibm.com/"
  - source cloudctl.sh
  - source install_mcm_chart.sh

before_script:
  - "export DISPLAY=:99.0"
  - if [ $(uname -m) == 'x86_64' ]; then sh -e /etc/init.d/xvfb start; else echo 's390x or ppc64le - skipping'; fi

script:
 - npm install
 - npm run test:e2e
