sudo: required
language: node_js

addons:
  packages:
    - openjdk-8-jdk
  chrome: stable

services:
  - xvfb

# Only build on master, and release branches
branches:
  only:
    - master
    - /^release-[0-9]+\..*$/

before_install:
  - sh download-clis.sh
  #- sh install_search_chart.sh
  - sleep 60 # Wait until search components initialize.

script:
  - npm install
  - npm run test:e2e
